### PR TITLE
more efficient, consistent generation. added relaxation demo to example

### PR DESCRIPTION
**Pull request by kylemcdonald**

### CODE REVIEW

**Comment by madc** [comment]
Thanks for the PR. I mostly understand, what you did there, just a couple of quick questions:

Why did you remove the project files for windows and linux, but left the xcode one in?
Why did you declare `vector<ofPoint> points` in `ofApp.cpp` and not `ofApp.h`?

**Comment by kylemcdonald** [comment]
whoops! good catches.
1. i meant to remove all the project files. the project generator is way better at keeping project files up to date now.
2. vector<ofPoint> points should be in the .h, you are correct.

**Comment by madc** [comment]
If you could update the PR, i'd be happy to merge it.

**Comment by kylemcdonald** [comment]
PR updated per discussion.

**Comment by madc** [comment]
Thanks.

**Pull request merged**
